---
- hosts: all
  become: true
  pre_tasks:

 - name: install updates (CentOS)
   dnf:
     update_only: yes
     update_cache: yes
   when: ansbile_distribution == "CentOS"

 - name: install updates (Ubuntu)
   apt:
     upgrade: dist
     update_cache: yes
   when: ansbile_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  task:

 - name: install apache and php for Ubuntu servers
   apt:
     name:
       - apache2
       - libapache2-mod-php
     state: latest
     update_cache: yes
   when: ansible_distribution == "Ubuntu"

 - name: install apache and php for CentOS servers
   dnf:
     name:
       - httpd
       - php
     state: latest
   when: ansbile_distribution == "CentOS"
